


exports.config = {
    MAX_NODES          : 10,
    SIMULATION_TIMEOUT : 3000,
    PULSE_PERIODICITY  : 500,
    MAX_KEYS_COUNT     : 100,
    MAX_TRANSACTIONS   : 1000,
    MAX_TRANSACTION_TIME: 1000,
    NETWORK_DELAY      : 500
};


GLOBAL_MAX_TRANSACTION_TIME = exports.config.MAX_TRANSACTION_TIME / 1000;
